/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/* eslint-disable no-undef */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  hideDMNotes: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Rules',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-rules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Setting',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-setting',
        },
      ],
    },
    {
      type: 'doc',
      label: 'Sources',
      id: 'sources',
    },
  ],

  justDMNotes: [
    {
      type: 'category',
      label: 'DM Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: '03-dmNotes',
        },
      ],
    },
  ],
};

module.exports = sidebars;
